# Accumulator configuration
NUM_BANKS = 7
NUM_CELLS_PER_BANK = 20

# Limits
CELL_VOLT_MIN = 2.5
CELL_VOLT_MAX = 4.2

CELL_TEMP_DISCHARGE_MIN = -20
CELL_TEMP_DISCHARGE_MAX = 60
CELL_TEMP_CHARGE_MIN = 0
CELL_TEMP_CHARGE_MAX = 45
