// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: ics_test

#ifndef _ICS_TEST_UI_H
#define _ICS_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Bar3;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_intervar52);
LV_FONT_DECLARE( ui_font_robotf);
LV_FONT_DECLARE( ui_font_roboto20);
LV_FONT_DECLARE( ui_font_roboto42);
LV_FONT_DECLARE( ui_font_roboto52);
LV_FONT_DECLARE( ui_font_roboto60);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
