// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name:  color_test

#ifndef __COLOR_TEST_UI_H
#define __COLOR_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Colorwheel1;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
