#ifndef INC_FEB_CAN_ID_H_
#define INC_FEB_CAN_ID_H_

// Sensor IDS
#define FEB_CAN_ID_AIRSPEED 0x411
#define FEB_CAN_ID_COOLANT_TEMP 0x510
#define FEB_CAN_ID_COOLANT_FLOW 0x511
#define FEB_CAN_ID_IMU 0x521
#define FEB_CAN_ID_STRAIN_GAUGE 0x522
#define FEB_CAN_ID_THERMOCOUPLE_1 0x523
#define FEB_CAN_ID_WHEEL_SPEED_SENSOR 0x524

#endif
