# **************************************** Static CAN IDs ****************************************

# Charger
FEB_CAN_ID_CHARGER_BMS = 0x1806e5f4
FEB_CAN_ID_CHARGER_CCS = 0x18ff50e5

# IVT
FEB_CAN_ID_IVT_COMMAND = 0x411
FEB_CAN_ID_IVT_DEBUG = 0x510
FEB_CAN_ID_IVT_RESPONSE = 0x511
FEB_CAN_ID_IVT_CURRENT = 0x521
FEB_CAN_ID_IVT_VOLTAGE_1 = 0x522
FEB_CAN_ID_IVT_VOLTAGE_2 = 0x523
FEB_CAN_ID_IVT_VOLTAGE_3 = 0x524
FEB_CAN_ID_IVT_TEMPERATURE = 0x525
FEB_CAN_ID_IVT_POWER = 0x526
FEB_CAN_ID_IVT_CURRENT_COUNTER = 0x527
FEB_CAN_ID_IVT_ENERGY_COUNTER = 0x528

# **************************************** Dynamic CAN IDs ****************************************

# BMS
FEB_CAN_ID_BMS_TEMPERATURE = 0x0
FEB_CAN_ID_BMS_VOLTAGE = 0x1
FEB_CAN_ID_BMS_STATE = 0x2
