// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ICS

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedField = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_speedField, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedField, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_speedField, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedField,"0");
lv_obj_set_style_text_color(ui_speedField, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedField, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedField, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonField = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_buttonField, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_buttonField, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_buttonField, 0 );
lv_obj_set_y( ui_buttonField, 100 );
lv_obj_set_align( ui_buttonField, LV_ALIGN_CENTER );
lv_label_set_text(ui_buttonField,"00000000");
lv_obj_set_style_text_color(ui_buttonField, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_buttonField, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_buttonField, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_speedLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedLabel, 0 );
lv_obj_set_y( ui_speedLabel, -100 );
lv_obj_set_align( ui_speedLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedLabel,"Speed");
lv_obj_set_style_text_color(ui_speedLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}
