// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CANViewer

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_canIdLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_canIdLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_canIdLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_canIdLabel, -250 );
lv_obj_set_y( ui_canIdLabel, -50 );
lv_obj_set_align( ui_canIdLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_canIdLabel,"00");
lv_obj_set_style_text_color(ui_canIdLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_canIdLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_canIdLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dlcLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_dlcLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dlcLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dlcLabel, -100 );
lv_obj_set_y( ui_dlcLabel, -50 );
lv_obj_set_align( ui_dlcLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_dlcLabel,"00");
lv_obj_set_style_text_color(ui_dlcLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dlcLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dlcLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_dataLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dataLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dataLabel, 160 );
lv_obj_set_y( ui_dataLabel, -50 );
lv_obj_set_align( ui_dataLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_dataLabel,"00000000");
lv_obj_set_style_text_color(ui_dataLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dataLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -250 );
lv_obj_set_y( ui_Label2, 0 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"CAN ID");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -100 );
lv_obj_set_y( ui_Label1, 0 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"DLC");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 160 );
lv_obj_set_y( ui_Label3, 0 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"DATA");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonField = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_buttonField, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_buttonField, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_buttonField, 0 );
lv_obj_set_y( ui_buttonField, 80 );
lv_obj_set_align( ui_buttonField, LV_ALIGN_CENTER );
lv_label_set_text(ui_buttonField,"00000000");
lv_obj_set_style_text_color(ui_buttonField, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_buttonField, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_buttonField, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 0 );
lv_obj_set_y( ui_Label4, 140 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Button State");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

}
