// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: driverux

#ifndef _DRIVERUX_UI_H
#define _DRIVERUX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1348218614);   // assets/formulaelectricberkeley_logo-removebg-preview.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
